[versions]
android-compileSdk = "36"
android-minSdk = "26"
android-targetSdk = "36"
activityKtx = "1.8.0"
adapterRxjava2 = "2.9.0"
appcompat = "1.6.1"
autofill = "1.1.0"
cardStackView = "2.3.4"
emoji2Bundled = "1.4.0"
firebaseUiStorage = "7.2.0"
flexbox = "3.0.0"
fragmentKtx = "1.6.2"
hiltCompiler = "1.1.0"
kotlinParcelizeRuntime = "2.0.0"
kotlinpoet = "1.14.2"
kotlinpoetKsp = "1.14.2"
library = "2.0.0"
lifecycleExtensions = "2.2.0"
material = "1.10.0"
constraintlayout = "2.1.4"
coroutines = "1.8.1"
numberPicker = "2.4.13"
pagingRuntime = "3.3.2"
preferenceKtx = "1.2.1"
retrofit = "2.10.0"
room = "2.6.0"
hilt = "2.57.2"
lifecycle = "2.6.2"
kotlinx-serialization = "1.9.0"
gson = "2.10.1"
ksp = "2.1.0-1.0.29"
roomPaging = "2.6.0"
rxandroid = "2.1.1"
rxjava = "2.2.10"
rxjavaVersion = "3.1.4"
rxkotlin = "2.0.0-RC1"
glide = "4.16.0"
okhttp3Integration = "4.12.0"
loggingInterceptor = "4.9.0"
firebaseBom = "32.6.0"
firebaseCrashlyticsGradle = "3.0.3"
googleServices = "4.4.2"
eventbus = "3.3.1"
circleindicator = "2.1.6"
androidsvgAar = "1.4"
lottie = "6.6.2"
androidImageCropperVersion = "4.6.0"
cameraCore = "1.3.1"
cameraLifecycle = "1.4.2"
playServicesMlkitSubjectSegmentation = "16.0.0-beta1"
playServicesMlkitTextRecognition = "19.0.1"
playServicesMlkitTextRecognitionChinese = "16.0.0"
playServicesMlkitTextRecognitionCommon = "19.1.0"
playServicesMlkitTextRecognitionDevanagari = "16.0.0"
playServicesMlkitTextRecognitionVersion = "19.0.0"
symbolProcessingApi = "1.9.10-1.0.13"
paging = "3.3.6"
material3Android = "1.4.0"
composeBom = "2024.09.00"
agp = "8.9.1"
kotlin = "2.1.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
googleGmsGoogleServices = "4.4.4"
firebaseDatabase = "22.0.1"
navigationCompose = "2.9.5"
material3 = "1.4.0"
navigationRuntimeKtx = "2.9.5"
coil = "2.4.0"
composeRuntimeLivedata = "1.6.0"
accompanistPager = "0.30.1"
hiltNavigationCompose = "1.2.0"
glancePreview = "1.1.1"
foundation = "1.9.3"
places = "5.0.0"
pagingRuntimeKtx = "3.3.6"
roomKtx = "2.8.2"
uiText = "1.9.3"
credentials = "1.5.0"
credentialsPlayServicesAuth = "1.5.0"
googleid = "1.1.1"
firebase-auth = "22.3.0"
firebase-firestore = "25.1.1"
roomKtxVersion = "2.8.3"
workRuntimeKtx = "2.11.0"
firebaseDynamicLinksKtx = "22.1.0"
viewbinding = "7.1.0"
recyclerview = "1.3.2"
foundationVersion = "1.9.5"
composeAnimation = "1.7.3"
composeConstraint = "1.1.0"
composeMaterialIconsExtended = "1.7.3"
composeCompiler = "1.5.12"
androidxFoundation = "1.10.0"
firebaseFirestoreKtx = "26.0.2"
navigationComposeVersion = "2.9.6"
androidxRoomKtx = "2.8.4"
ui = "1.10.0"
uiUnit = "1.10.0"

[libraries]
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraLifecycle" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraCore" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraLifecycle" }
androidx-camera-video = { module = "androidx.camera:camera-video", version.ref = "cameraLifecycle" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraLifecycle" }
adapter-rxjava2 = { module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "adapterRxjava2" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-autofill = { module = "androidx.autofill:autofill", version.ref = "autofill" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-emoji2 = { module = "androidx.emoji2:emoji2", version.ref = "emoji2Bundled" }
androidx-emoji2-bundled = { module = "androidx.emoji2:emoji2-bundled", version.ref = "emoji2Bundled" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompiler" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }
androidx-paging-runtime-v332 = { module = "androidx.paging:paging-runtime", version.ref = "pagingRuntime" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "roomPaging" }
card-stack-view = { module = "com.yuyakaido.android:card-stack-view", version.ref = "cardStackView" }
firebase-storage-ktx = { module = "com.google.firebase:firebase-storage-ktx" }
firebase-ui-storage = { module = "com.firebaseui:firebase-ui-storage", version.ref = "firebaseUiStorage" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlin-parcelize-runtime = { module = "org.jetbrains.kotlin:kotlin-parcelize-runtime", version.ref = "kotlinParcelizeRuntime" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoetKsp" }
library = { module = "com.ogaclejapan.smarttablayout:library", version.ref = "library" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-config-ktx = { module = "com.google.firebase:firebase-config-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
firebase-messaging-ktx = { module = "com.google.firebase:firebase-messaging-ktx" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
androidx-viewbinding = { group = "androidx.databinding", name = "viewbinding", version.ref = "viewbinding" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
androidsvg-aar = { module = "com.caverock:androidsvg-aar", version.ref = "androidsvgAar" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "loggingInterceptor" }
okhttp3-integration = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "okhttp3Integration" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbus" }
circleindicator = { module = "me.relex:circleindicator", version.ref = "circleindicator" }
rxandroid = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxandroid" }
rxjava = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava" }
rxjava3-rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjavaVersion" }
rxkotlin = { module = "io.reactivex:rxkotlin", version.ref = "rxkotlin" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
vanniktech-android-image-cropper = { module = "com.vanniktech:android-image-cropper", version.ref = "androidImageCropperVersion" }
play-services-mlkit-text-recognition = { module = "com.google.android.gms:play-services-mlkit-text-recognition", version.ref = "playServicesMlkitTextRecognition" }
play-services-mlkit-text-recognition-chinese = { module = "com.google.android.gms:play-services-mlkit-text-recognition-chinese", version.ref = "playServicesMlkitTextRecognitionChinese" }
play-services-mlkit-text-recognition-common = { module = "com.google.android.gms:play-services-mlkit-text-recognition-common", version.ref = "playServicesMlkitTextRecognitionCommon" }
play-services-mlkit-text-recognition-japanese = { module = "com.google.android.gms:play-services-mlkit-text-recognition-japanese", version.ref = "playServicesMlkitTextRecognitionChinese" }
play-services-mlkit-text-recognition-korean = { module = "com.google.android.gms:play-services-mlkit-text-recognition-korean", version.ref = "playServicesMlkitTextRecognitionChinese" }
play-services-mlkit-text-recognition-v1900 = { module = "com.google.android.gms:play-services-mlkit-text-recognition", version.ref = "playServicesMlkitTextRecognitionVersion" }
gms-play-services-mlkit-text-recognition-devanagari = { module = "com.google.android.gms:play-services-mlkit-text-recognition-devanagari", version.ref = "playServicesMlkitTextRecognitionDevanagari" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
androidx-paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "paging" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "composeRuntimeLivedata" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanistPager" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanistPager" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-glance-preview = { group = "androidx.glance", name = "glance-preview", version.ref = "glancePreview" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
places = { group = "com.google.android.libraries.places", name = "places", version.ref = "places" }
androidx-paging-runtime-ktx = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "pagingRuntimeKtx" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }
androidx-compose-ui-text = { group = "androidx.compose.ui", name = "ui-text", version.ref = "uiText" }
androidx-credentials = { group = "androidx.credentials", name = "credentials", version.ref = "credentials" }
androidx-credentials-play-services-auth = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "credentialsPlayServicesAuth" }
googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleid" }
firebase-auth = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firebase-auth" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore-ktx", version.ref = "firebase-firestore" }
number-picker = { module = "io.github.ShawnLin013:number-picker", version.ref = "numberPicker" }
androidx-room-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtxVersion" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
firebase-dynamic-links-ktx = { group = "com.google.firebase", name = "firebase-dynamic-links-ktx", version.ref = "firebaseDynamicLinksKtx" }
androidx-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundationVersion" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "composeMaterialIconsExtended" }
androidx-compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "composeAnimation" }
androidx-compose-animation-graphics = { group = "androidx.compose.animation", name = "animation-graphics", version.ref = "composeAnimation" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose" }
androidx-compose-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "composeConstraint" }
foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "androidxFoundation" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationComposeVersion" }
androidx-room-room-ktx2 = { group = "androidx.room", name = "room-ktx", version.ref = "androidxRoomKtx" }
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "ui" }
androidx-compose-ui-unit = { group = "androidx.compose.ui", name = "ui-unit", version.ref = "uiUnit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }